// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxs9hbvEXe7a-jVABAzSVIz4fyBxg2Ek',
    appId: '1:480309562020:web:08dd655be59d1d4e263431',
    messagingSenderId: '480309562020',
    projectId: 'pasien-50420462-247e6',
    authDomain: 'pasien-50420462-247e6.firebaseapp.com',
    storageBucket: 'pasien-50420462-247e6.appspot.com',
    measurementId: 'G-ZV6P4ZGWZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdNLDtH01xEgslGPcRAVZx-AtJjQq-aGs',
    appId: '1:480309562020:android:c1ec043f5598a9f7263431',
    messagingSenderId: '480309562020',
    projectId: 'pasien-50420462-247e6',
    storageBucket: 'pasien-50420462-247e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFHFxLKNcz2HtdQ7VJBLBrChi2KkZB9Y',
    appId: '1:480309562020:ios:3f37f4494a4f8d73263431',
    messagingSenderId: '480309562020',
    projectId: 'pasien-50420462-247e6',
    storageBucket: 'pasien-50420462-247e6.appspot.com',
    iosClientId: '480309562020-g1v2ohk9krdsajuhvb2vpol6rbt5cbbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsku50420462',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFHFxLKNcz2HtdQ7VJBLBrChi2KkZB9Y',
    appId: '1:480309562020:ios:3f37f4494a4f8d73263431',
    messagingSenderId: '480309562020',
    projectId: 'pasien-50420462-247e6',
    storageBucket: 'pasien-50420462-247e6.appspot.com',
    iosClientId: '480309562020-g1v2ohk9krdsajuhvb2vpol6rbt5cbbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsku50420462',
  );
}
